In [ ]:
# Binary file Extension in numpy is .npy

In [ ]:
import numpy as np
# create a numpy array
array1 = np.array([[1, 3, 5],[7, 9, 11]])
# save the array to a file
np.save('D:\\PYTHON FULL STACK\\LibraryPrograms\\MatPlotLib\\file1.npy', array1)
print("Ndarray object Data saved into the Binary File(.npy)")


Ndarray object Data saved into the Binary File(.npy)


In [11]:
import numpy as np
# load the Saved the numpy array
loaded_array = np.load('D:\\PYTHON FULL STACK\\LibraryPrograms\\MatPlotLib\\file1.npy')
# display the loaded array 
print(loaded_array)

[[ 1  3  5]
 [ 7  9 11]]


In [12]:

#!      text file
import numpy as np
# create a numpy array
array2 = np.array([[1,3,5],[7,9,11]])
# save the array to the file
np.savetxt('D:\\PYTHON FULL STACK\\LibraryPrograms\\MatPlotLib\\kvr.txt',array2)
print("Ndarray object Data saved into the Text File(.npy)")

Ndarray object Data saved into the Text File(.npy)


In [13]:
import numpy as np
# load the saved numpy array
loaded_array=np.loadtxt('D:\\PYTHON FULL STACK\\LibraryPrograms\\MatPlotLib\\kvr.txt')
#Display the load array
print(loaded_array)

[[ 1.  3.  5.]
 [ 7.  9. 11.]]


In [14]:
import numpy as np
# load the saved numpy array
loaded_array =np.loadtxt('D:\\PYTHON FULL STACK\\LibraryPrograms\\MatPlotLib\\kvr.txt')
# Display the load array
print(loaded_array.astype("int32"))

[[ 1  3  5]
 [ 7  9 11]]


In [ ]:

#!         Save Multiple NumPy Array File(.npz Files)   # there is the Extra z is there
#* there the z meaning is that multiple file is zipping together


In [24]:
l1 = [10,20,30,40]
l2 = ["RS","TR","SR","KV"]
x = zip(l1,l2)
print(x)
print(type(x))
for i in x:
    #print(i)
    print(f"{i[0]} ---> {i[1]}")
print("------------------")    
for k,v in x:
    print(k,"--->",v)    

<class 'zip'>
10 ---> RS
20 ---> TR
30 ---> SR
40 ---> KV
------------------


In [25]:
#Save Multiple NumPy Array File(.npz Files)
import numpy as np
# Create two numpy array
array1 = np.array([2, 6, 10])
array2 = np.array([4, 8, 12])
# save the two arrays into a single file
np.savez('D:\\PYTHON FULL STACK\\LibraryPrograms\\MatPlotLib\\file2.npz', k = array1, v = array2)
print("Multiple Ndarray objects Data saved into the Single File (.npz)")

Multiple Ndarray objects Data saved into the Single File (.npz)


In [26]:

#!  Load Multiple NumPy Array File--Reading the Data from npz files

import numpy as np

# load the saved arrays 
load_data = np.load('D:\\PYTHON FULL STACK\\LibraryPrograms\\MatPlotLib\\file2.npz')

# retrieve the arrays using their names
array1 = load_data['k']
array2 = load_data['v']

# display the loaded arrays
print("--------------------------------------")
print(array1)
print("--------------------------------------")
print(array2)
print("--------------------------------------")

--------------------------------------
[ 2  6 10]
--------------------------------------
[ 4  8 12]
--------------------------------------
